version: '2'
services:
    php:
        build: ./php-fpm
        ports:
            - 9000:9000
        volumes:
            - .:/var/www/project
        environment:
            DB_PORT: 3306
            DB_HOST: db
        links:
            - db
    nginx:
        image: nginx
        ports:
            - 80:80
        links:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/project
            - ./docker/logs/nginx/:/var/log/nginx
    db:
        image: mysql:5.7.19
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql:/data
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: php-app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
